// categorias.js
window.categorias = [
  {
    id: 1,
    nombre: "Laborales",
    catalogos: [
      "Suplantación EMO",
      "Reuniones Extra Laborales en contra de MCP",
      "Incumplir Protocolo COVID-19",
      "Incumplimiento Políticas de Protección Empresarial",
      "Incumplimiento a la Política de Alcohol y Drogas",
      "Incumplido los reglamentos internos de su compañia"
    ]
  },
  {
    id: 2,
    nombre: "Antecedentes Penales y Judiciales",
    catalogos: [
      "Sin Antecedentes",
      "Abandono de Destino",
      "Abandono de mujer gestante",
      "Abigeo",
      "Aborto",
      "Aborto Consentido",
      "Aborto Preterintecional",
      "Acoso",
      "Actos contra el pudor",
      "Apropiación Ilícita",
      "Apropiación Ilícita y Estafa",
      "Apropiación Irregular",
      "Asalto a mano armada",
      "Asociación Ilícita Para Delinquir; Tráfico Ilícito de Drogas; Peligro Común",
      "Atentado contra el derecho de sufragio",
      "Chantaje Sexual",
      "Coacción",
      "Coacción; Deserción",
      "Conducción de Vehículo en estado de ebriedad",
      "Conducir en estado de ebriedad",
      "Conducir en estado de ebriedad; Deserción",
      "Contra los derechos de autor",
      "Contrabando",
      "Corrupción",
      "Corrupción de Funcionario",
      "Daño Agravado",
      "Daño Simple",
      "Daños",
      "Daños al Patrimonio",
      "Defraudación",
      "Delito contra el Patrimonio",
      "Delito de Contaminación del ambiente",
      "Delitos conta la Libertad de Sufragio",
      "Delitos contra el derecho de Sufragio",
      "Delitos Contra la Administración Pública",
      "Delitos Contra la Función Jurisdiccional",
      "Delitos contra la Paz Pública y Robo Agravado",
      "Delitos contra la salud publica en la modalidad de violación de medidas sanitarias",
      "Delitos Contra la Tranquilidad Pública;Delito de Asociación Ilícita para Delinquir",
      "Delitos Económicos",
      "Delitos Monetarios",
      "Depredación de flora y fauna legalmente protegidas",
      "Deserción",
      "Desobediencia y Resistencia a la Autoridad",
      "Desobediencia y Resistencia a la Autoridad;Lesiones Culposas",
      "Disturbios",
      "Estafa",
      "Exposición o abandono peligroso",
      "Extorsión",
      "Fabricación y falsificación de moneda",
      "Falsa declaración",
      "Falsedad Genérica",
      "Falsedad Genérica; Falsa declaración en procedimiento administrativo; Estafa",
      "Falsedad Ideológica",
      "Falsedad Ideológica; Organización Criminal; Estafa Agravada",
      "Falsificación de Documentos",
      "Falsificación de Documentos; Falsedad Genérica",
      "Falta Grave",
      "Faltas",
      "Faltas contra el Patrimonio",
      "Faltas contra las personas",
      "Feminicidio",
      "Fraude Procesal",
      "Homicidio",
      "Homicidio Calificado",
      "Homicidio Culposo",
      "Homicidio Culposo; Delitos contra la Fe Pública",
      "Homicidio Simple; Lesiones culposas",
      "Homicidio Simple; Omisión Asistencia Familiar",
      "Hurto",
      "Hurto Agravado",
      "Hurto Agravado; Deserción",
      "Hurto Agravado; Lesiones Leves",
      "Hurto Agravado; Lesiones Leves; Deserción",
      "Hurto Simple",
      "Impedimento de Salida del País Caducado por Alimentos",
      "Impedimento de Salida del País por Omisión de Asistencia Familia",
      "Impedimento de Salida por Omisión a la Asistencia Familiar",
      "Imprudencia en la Conducción Vehicular",
      "Inducción a la fuga de menor",
      "Lesiones Culposas",
      "Lesiones Culposas; Daño Simple",
      "Lesiones Culposas; Lesiones Graves",
      "Lesiones Dolosas",
      "Lesiones Graves",
      "Lesiones Graves por Violencia Familiar",
      "Lesiones Graves; Deserción",
      "Lesiones Leves",
      "Lesiones Leves por Violencia Familiar",
      "Lesiones Leves por Violencia Familiar(formas agravadas)",
      "Lesiones Leves; Lesiones Culposas",
      "Libramientos Indebidos (emitir cheque sin fondos)",
      "Material sin autorización",
      "Negociación incompatible; Corrupción de Funcionarios; Resistencia a la Autoridad",
      "Omisión a la Asistencia Familiar",
      "Omisión Asistencia Familiar",
      "Omisión Asistencia Familiar ",
      "Omisión Asistencia Familiar, Deserción",
      "Omisión Asistencia Familiar, Homicidio Simple",
      "Omisión Asistencia Familiar; Deserción",
      "Omisión Asistencia Familiar; Lesiones Graves",
      "Omisión Asistencia Familiar; Lesiones Leves; Violación Libertad Sexual",
      "Omisión Asistencia Familiar; Peligro Común",
      "Omisión Asistencia Familiar; y Homicidio ",
      "Omisión Asistencia Familiar;Faltas contra las Personas",
      "Omisión Asistencia Familiar;Hurto Agravado",
      "Omisión de Asistencia Familiar",
      "Omisión de Socorro",
      "Omisión, rehusamiento o demora de actos funcionales",
      "Peculado",
      "Peligro Común",
      "Presunta Violación Sexual",
      "Proxenetismo",
      "Receptación",
      "Resistencia a la Autoridad",
      "Reuniones Extra Laborales en contra de MCP",
      "Robo",
      "Robo Agravado",
      "Robo Agravado y Hurto Simple",
      "Robo Agravado; Peligro Común",
      "Secuestro",
      "Seducción",
      "Suplantación EMO",
      "Sustracción de Menor; Omisión Asistencia Familiar",
      "Tenencia Ilegal de Armas de Fuego",
      "Tentativa de Homicidio",
      "Tentativa de Secuestro",
      "Terrorismo",
      "Terrorismo Agravado",
      "Tocamientos Indebidos",
      "Tocamientos, actos de connotación sexual o actos libidinosos sin Consentimiento",
      "Tortura",
      "Tráfico Ilegal de Armas de Fuego",
      "Tráfico ilegal de productos forestales maderables",
      "Tráfico Ilícito de Drogas",
      "Tráfico Ilícito de Drogas y Deserción",
      "Trata de Personas",
      "Uso de Documentos Falsos",
      "Usurpación",
      "Usurpación Agravada",
      "Usurpación; Daños al Patrimonio",
      "Usurpación; Robo agravado",
      "Violación de Domicilio",
      "Violación de la Libertad Sexual",
      "Violación de la Libertad Sexual; Hurto Simple",
      "Violación de Medidas Sanitaria",
      "Violación Libertad Sexual",
      "Violación Sexual",
      "Violencia Familiar (Maltrato Físico y Psicológico)",
      "Violencia Familiar (Maltrato Físico)"
    ]
  }
];
